export enum ColumnValueTypes {
  text = 'text',
  imageList = 'image-list',
  numeric = 'numeric',
  date = 'date',
  dateTime = 'date-time',
  selection = 'selection',
  checkbox = 'checkbox',
  string = 'string',
  number = 'number',
  boolean = 'boolean',
  array = 'array',
  multi = 'multi',
  single = 'single',
  input = 'input',
  percentage = 'percentage',
  timespan = 'timespan',
  link = 'link',
  listbox = 'listbox',
  yesNoType = 'yesNoType',
  textTranslate = 'textTranslate',
  price = 'price'
}